version: '3.8'

networks:
  dev_network:

services:

  db:
    build: db
    ports:
      - "5432:5432"
    container_name: db_main
    networks:
      dev_network:
        aliases:
          - db-main

  app:
    build:
      context: .
      args:
        PG_DSN: 'postgresql://admin:1234@db-main:5432/flask_netology'
    ports:
      - "5000:5000"
    container_name: app
    depends_on:
      - db
    networks:
      dev_network:
        aliases:
          - flask_api
    restart:
      always
    volumes:
      - ./:/app
